Add xlsx report
omg-dds/dds-rtps pull request #20
Opened 2024-02-19 19:09 UTC by angelrti

This PR inclues a way of creating an XLSX report from the JUnit generated after running the tests. You can see an example at the bottom (interoperability report artifact): https://github.com/rticommunity/dds-rtps/actions/runs/7963829130

I'll be merging this PR by Feb 29th, so please, add your feedback before that date.

2024-02-20 07:50 UTC, MiguelCompany approved these changes

2024-02-27 15:33 UTC, jrw972 requested changes

2024-02-27 15:33 UTC, jrw972 commented on generate_xlsx_report.py
> +            return 'Object Computing Incorporated (OCI)'
```suggestion
            return 'OpenDDS Foundation'
```

2024-02-29 20:09 UTC, jrw972 approved these changes

2024-03-01 08:43 UTC, merged