This PR creates an html webpage that is uploaded as a github page
omg-dds/dds-rtps pull request #39
Opened 2024-05-29 19:36 UTC by angelrti

The html documentation is generated automatically (triggered manually) from the latest available report. The html documentation is similar to this: https://rticommunity.github.io/dds-rtps/index.html

2024-05-29 20:45 UTC, jrw972 requested changes

2024-05-29 20:45 UTC, jrw972 commented on doc/index.rst
> +.. RTI Connext Gateway documentation master file, created by
Probably need to change this.

2024-05-29 23:12 UTC, angelrti commented on doc/index.rst
> +.. RTI Connext Gateway documentation master file, created by
ohh nice catch, thank you!

2024-05-30 16:25 UTC, jrw972 approved these changes

2024-06-11 20:23 UTC, merged